version: "3"

services:
  pihole:
    restart: unless-stopped
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80
    environment:
      TZ: 'Europe/Berlin' 
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
