version: "3"

services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp 
      - 80:80/tcp
      - 3000:3000/tcp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf

